apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    annotations:
      helm.sh/resource-policy: keep
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
      prometheus-operator-validated: "true"
    creationTimestamp: "2024-08-06T01:55:24Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
      prometheus: longhorn
      role: alert-rules
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:helm.sh/resource-policy: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:objectset.rio.cattle.io/hash: {}
            f:prometheus: {}
            f:role: {}
        f:spec:
          .: {}
          f:groups:
            .: {}
            k:{"name":"longhorn.rules"}:
              .: {}
              f:name: {}
              f:rules: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:55:24Z"
    name: prometheus-longhorn-rules
    namespace: longhorn-system
    resourceVersion: "10831"
    uid: 5335b8d1-9ace-4524-b730-d90eaa8871bb
  spec:
    groups:
    - name: longhorn.rules
      rules:
      - alert: LonghornVolumeActualSpaceUsedWarning
        annotations:
          description: The actual space used by Longhorn volume on node is at 90%
            capacity for more than 5 minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: The actual used space of Longhorn volume is over 90% of the capacity.
        expr: (longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes)
          * 100 > 90
        for: 5m
        labels:
          issue: The actual used space of Longhorn volume on is high.
          severity: warning
      - alert: LonghornVolumeStatusCritical
        annotations:
          description: Longhorn volume on is Fault for more than 5 minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: Longhorn volume is Fault
        expr: longhorn_volume_robustness == 3
        for: 5m
        labels:
          issue: Longhorn volume  is Fault.
          severity: critical
      - alert: LonghornVolumeStatusWarning
        annotations:
          description: Longhorn volume is Degraded for more than 5 minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: Longhorn volume is Degraded
        expr: longhorn_volume_robustness == 2
        for: 5m
        labels:
          issue: Longhorn volume is Degraded.
          severity: warning
      - alert: LonghornNodeStorageWarning
        annotations:
          description: The used storage of node is at 70% capacity for more than 5
            minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: The used storage of node is over 70% of the capacity.
        expr: (longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes)
          * 100 > 70
        for: 5m
        labels:
          issue: The used storage of node is high.
          severity: warning
      - alert: LonghornDiskStorageWarning
        annotations:
          description: The used storage of disk is at 70% capacity for more than 5
            minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: The used storage of disk is over 70% of the capacity.
        expr: (longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > 70
        for: 5m
        labels:
          issue: The used storage of disk on node is high.
          severity: warning
      - alert: LonghornNodeDown
        annotations:
          description: There are Longhorn nodes which have been offline for more than
            5 minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: Longhorn nodes is offline
        expr: (avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition="ready"}
          == 1) or on() vector(0)) > 0
        for: 5m
        labels:
          issue: There are Longhorn nodes are offline
          severity: critical
      - alert: LonghornIntanceManagerCPUUsageWarning
        annotations:
          description: Longhorn instance manager has CPU Usage / CPU request is over
            300% for more than 5 minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: Longhorn instance manager has CPU Usage / CPU request is over 300%.
        expr: (longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu)
          * 100 > 300
        for: 5m
        labels:
          issue: Longhorn instance manager on consumes 3 times the CPU request.
          severity: warning
      - alert: LonghornNodeCPUUsageWarning
        annotations:
          description: Longhorn node has CPU Usage / CPU capacity is over 90% for
            more than 5 minutes.
          runbook_url: https://longhorn.io/docs/1.3.0/monitoring/metrics/
          summary: Longhorn node experiences high CPU pressure for more than 5m.
        expr: (longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu)
          * 100 > 90
        for: 5m
        labels:
          issue: Longhorn node experiences high CPU pressure.
          severity: warning
kind: List
metadata:
  continue: "null"
  resourceVersion: "770282"
