apiVersion: v1
items:
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-06T01:53:30Z"
    name: default
    namespace: cattle-monitoring-system
    resourceVersion: "8761"
    uid: ef515b01-2bda-4ddf-86bb-fa4d9e5bca09
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQzW7jMAyEX2XBs51dO/8C9lD0UqDHBr3TMhOrkciAol0UQd69cJpDCvQnx8FoPnHmCHgIz6Q5CIODoYICsDdJ0rM9kQ7B0533o9rInhicaU8F7AO34ODzCyggkWGLhuCOgMxiaEE4j1KaF/KWySYaZOLRLNIkyN8wgjqKqfTCphIjaek7VCuVdiGbnhlQfEuQVyYtd8P+Arqyhqr48xi4/f9AMd2P0F85jInAgSL7jrRMwsFEA+9uSuYD+jH+4V2ly/yWjRKcCvBK50qbkCgbpgM47mMsIGJD8cexOswdONgulnWFi2YxXTV1O2//Neumnm1X1XKK6zXOWpovfT2bjr9d+pwX/rLUbWef3gMAAP//nadcfSsCAAA
      objectset.rio.cattle.io/id: helm-controller-chart-registration
      objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
      objectset.rio.cattle.io/owner-name: rancher-monitoring
      objectset.rio.cattle.io/owner-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:40Z"
    labels:
      objectset.rio.cattle.io/hash: f6721a6b638b2d5d0b9b24f8173a99a4de57c243
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:automountServiceAccountToken: {}
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: helm-controller@harvesterdev1
      operation: Update
      time: "2024-08-06T01:56:40Z"
    name: helm-rancher-monitoring
    namespace: cattle-monitoring-system
    resourceVersion: "6561"
    uid: de3b574d-70b7-4091-8a9e-990c5bdb646f
- apiVersion: v1
  automountServiceAccountToken: true
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app: rancher-monitoring-alertmanager
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-monitoring-alertmanager
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 103.0.3_up45.31.1
      chart: rancher-monitoring-103.0.3_up45.31.1
      heritage: Helm
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:automountServiceAccountToken: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-alertmanager
    namespace: cattle-monitoring-system
    resourceVersion: "7568"
    uid: 2c58ec45-6592-4f49-a278-97234f97a6ef
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring-crd
      meta.helm.sh/release-namespace: cattle-monitoring-system
      objectset.rio.cattle.io/id: default-mcc-rancher-monitoring-crd-cattle-fleet-local-system
    creationTimestamp: "2024-08-06T01:54:23Z"
    labels:
      app: rancher-monitoring-crd-manager
      app.kubernetes.io/managed-by: Helm
      objectset.rio.cattle.io/hash: 2da503261617e9ea2da822d2da7cdcfccad847a9
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:54:23Z"
    name: rancher-monitoring-crd-manager
    namespace: cattle-monitoring-system
    resourceVersion: "3230"
    uid: acc2bdcf-0343-46fe-9c2e-11c8c21e4b2d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 9.1.5
      helm.sh/chart: grafana-6.59.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-grafana
    namespace: cattle-monitoring-system
    resourceVersion: "7564"
    uid: 60acdeed-94ae-4412-b03f-6db5f22bc4cb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kube-state-metrics
      app.kubernetes.io/part-of: kube-state-metrics
      app.kubernetes.io/version: 2.9.2
      helm.sh/chart: kube-state-metrics-5.8.1
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:release: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-kube-state-metrics
    namespace: cattle-monitoring-system
    resourceVersion: "7565"
    uid: fd83185f-9c63-4e69-9b60-819bc00e7bf6
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"meta.helm.sh/release-name":"rancher-monitoring","meta.helm.sh/release-namespace":"cattle-monitoring-system"},"labels":{"app":"rancher-monitoring-operator","app.kubernetes.io/component":"prometheus-operator","app.kubernetes.io/instance":"rancher-monitoring","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"rancher-monitoring-prometheus-operator","heritage":"Helm","release":"rancher-monitoring"},"name":"rancher-monitoring-operator","namespace":"cattle-monitoring-system"}}
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:53:30Z"
    labels:
      app: rancher-monitoring-operator
      app.kubernetes.io/component: prometheus-operator
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-monitoring-prometheus-operator
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 103.0.3_up45.31.1
      chart: rancher-monitoring-103.0.3_up45.31.1
      heritage: Helm
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:heritage: {}
            f:release: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2024-08-06T01:53:30Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-operator
    namespace: cattle-monitoring-system
    resourceVersion: "7569"
    uid: 6a5fad15-f01a-40e6-98e8-d31680b645b3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app: rancher-monitoring-patch-sa
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-patch-sa
    namespace: cattle-monitoring-system
    resourceVersion: "7571"
    uid: 81af3efa-c135-4fa5-a243-f82048034a71
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app: rancher-monitoring-prometheus
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-monitoring-prometheus
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 103.0.3_up45.31.1
      chart: rancher-monitoring-103.0.3_up45.31.1
      heritage: Helm
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-prometheus
    namespace: cattle-monitoring-system
    resourceVersion: "7570"
    uid: d7c435ae-1576-41ed-ab11-51b21070f8a2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-adapter
      app.kubernetes.io/part-of: prometheus-adapter
      app.kubernetes.io/version: v0.10.0
      helm.sh/chart: prometheus-adapter-4.2.0
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-prometheus-adapter
    namespace: cattle-monitoring-system
    resourceVersion: "7566"
    uid: ef789d6f-146f-4996-8fb7-e39c93b49ab4
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: prometheus-node-exporter
      app.kubernetes.io/part-of: prometheus-node-exporter
      app.kubernetes.io/version: 1.6.0
      helm.sh/chart: prometheus-node-exporter-4.20.0
      jobLabel: node-exporter
      release: rancher-monitoring
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:jobLabel: {}
            f:release: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-prometheus-node-exporter
    namespace: cattle-monitoring-system
    resourceVersion: "7567"
    uid: edf6c5c4-2ebc-45ba-9ebe-eabf8ca274b3
kind: List
metadata:
  resourceVersion: "770235"
