apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    labels:
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 9.1.5
      helm.sh/chart: grafana-6.59.0
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:roleRef: {}
        f:subjects: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    name: rancher-monitoring-grafana
    namespace: cattle-monitoring-system
    resourceVersion: "7667"
    uid: f8bac4b6-bc9f-440c-93aa-cb156bf7e1a4
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: rancher-monitoring-grafana
  subjects:
  - kind: ServiceAccount
    name: rancher-monitoring-grafana
    namespace: cattle-monitoring-system
kind: List
metadata:
  resourceVersion: "770235"
