apiVersion: v1
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQT0sDMRDFv4rMeVPb/aN1wVMvgngT77PZ6e7YZLIk44qUfndJW0EQtcfweL/M++0BJ36hmDgItDCvoIAdSw8tbIJseXjCCQrwpNijIrR7QJGgqBwk5WfoXslqIl1EDguLqo4WHK45M0Zy3tggGoNzFI0dMaqJNHDSeGRA8SshvAtFM8y7M+hbNK+Kq0eW/v6BnN9k6L8cQU/QQkSxI0XjwjCwDBfV0oQ2d0/ZV9Wkj6Tk4VCAjXQc88yekqKfoJU35wpw2JH7U9OIaYQWcLu+sVVZ9s1qiXXZd/Xarpe2wnLZNN22qeu72wqrMv92XnJymeWSqPm564LLD58BAAD//19QKNP/AQAA
      objectset.rio.cattle.io/id: helm-controller-chart-registration
      objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
      objectset.rio.cattle.io/owner-name: rancher-logging
      objectset.rio.cattle.io/owner-namespace: cattle-logging-system
    creationTimestamp: "2024-08-06T01:56:40Z"
    labels:
      objectset.rio.cattle.io/hash: af86c322d510a42db48c80c3a2055bf544973a32
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: helm-controller@harvesterdev1
      operation: Update
      time: "2024-08-06T01:56:40Z"
    name: chart-content-rancher-logging
    namespace: cattle-logging-system
    resourceVersion: "6533"
    uid: 391beda8-4a55-4073-b183-fbb2700a13fc
- apiVersion: v1
  data:
    config.json: '{"sink":"stdout","lastResourceVersionPositionPath":"/var/pos/event-tailer"}'
  kind: ConfigMap
  metadata:
    annotations:
      banzaicloud.com/last-applied: UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWyEkEGP2jAQhf/LnO0EKG2J771XqOql6WGIJ8HFjCPPJN1dlP++MgKJlZD2ZGv0vXlv3gU8KoK7QJe4D0P1TxKDg0sLEvjUgmtB1KdJWzAtRBTdk6Qpd/SbsoTEP5MELS/q8YrXM+Z6TFLTTKxWMUTKLSywGDiT4t0w4oGilB+OY3WaDpSZlKQKqQ4sitwRODhinkmUsvXU4xTVPu4F80TNeC7KD9xi4Db+dGHhZMSre4eqkWxMwxB4sPIqSmcwkP4z5T31lIk7EnB/yhnh1gk4uCvoRYnLTKoD8huGLqbJl5TzGuN4xDWY0r3mFIu90zyRgVNgDw5+lGS/HoM9OwAMTKHgzfdm43fY2M3Go936L41tfL+zuP26wxX51fZbD8vfZXkPAAD//1BLBwjJDgX7KAEAAPcBAABQSwECFAAUAAgACAAAAAAAyQ4F+ygBAAD3AQAACAAAAAAAAAAAAAAAAAAAAAAAb3JpZ2luYWxQSwUGAAAAAAEAAQA2AAAAXgEAAAAA
    creationTimestamp: "2024-08-06T01:56:46Z"
    labels:
      app.kubernetes.io/instance: harvester-default-event-tailer
      app.kubernetes.io/name: event-tailer
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:config.json: {}
        f:metadata:
          f:annotations:
            .: {}
            f:banzaicloud.com/last-applied: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"9792d8a9-22da-4d39-9df8-a458a0ed046f"}: {}
      manager: manager
      operation: Update
      time: "2024-08-06T01:56:46Z"
    name: harvester-default-event-tailer
    namespace: cattle-logging-system
    ownerReferences:
    - apiVersion: logging-extensions.banzaicloud.io/v1alpha1
      controller: true
      kind: EventTailer
      name: harvester-default
      uid: 9792d8a9-22da-4d39-9df8-a458a0ed046f
    resourceVersion: "7147"
    uid: 83d362e6-665c-485c-96ea-7dfc38021efe
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBeTCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNzIyOTA5MDgwMB4XDTI0MDgwNjAxNTEyMFoXDTM0MDgwNDAxNTEy
      MFowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTcyMjkwOTA4MDBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABEVIknm4Aj01WZVAC6VMFNVbO8v1ccUnvCgKi6+p
      L6BwKjjhJHscdm0sXEfbKmzVzYGI8PREFO7+HJ7vhOlZXBmjQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/mkvosSegv9Rg/1sb
      oX/NIEfYNDAKBggqhkjOPQQDAgNIADBFAiB11MuBH4WWBtvzoEkHidHZeDQokcxK
      wpTPtiVvDepgcgIhAKh3lx5DDJ2W/shLxKqDJRv9YzruvDsyJ9QLcM37IHpp
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-08-06T01:53:30Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:53:30Z"
    name: kube-root-ca.crt
    namespace: cattle-logging-system
    resourceVersion: "2315"
    uid: f5e2a538-adc9-4665-976b-5e21cebf6ba1
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"rancher-logging-77f858bbb7-j27z7_354d14d7-777b-4aa8-87e1-85070163dc87","leaseDurationSeconds":15,"acquireTime":"2024-08-06T01:56:45Z","renewTime":"2024-08-06T14:12:18Z","leaderTransitions":0}'
    creationTimestamp: "2024-08-06T01:56:45Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:control-plane.alpha.kubernetes.io/leader: {}
      manager: manager
      operation: Update
      time: "2024-08-06T14:12:18Z"
    name: logging-operator.logging.banzaicloud.io
    namespace: cattle-logging-system
    resourceVersion: "770261"
    uid: 21fb8bc8-7cb8-4bee-8c0d-f7969fad17bc
- apiVersion: v1
  data:
    fluent-bit.conf: |
      [SERVICE]
          Flush             1
          Grace             5
          Daemon            Off
          Log_Level         info
          Coro_Stack_Size   24576
          Parsers_File      parsers.conf

      [INPUT]
          Name              systemd
          Tag               rke2
          Path              /var/log/journal
          Systemd_Filter    _SYSTEMD_UNIT=rke2-server.service
          Systemd_Filter    _SYSTEMD_UNIT=rke2-agent.service
          Systemd_Filter    _SYSTEMD_UNIT=rancherd.service
          Systemd_Filter    _SYSTEMD_UNIT=rancher-system-agent.service
          Systemd_Filter    _SYSTEMD_UNIT=wicked.service
          Systemd_Filter    _SYSTEMD_UNIT=iscsid.service
          Systemd_Filter    _TRANSPORT=kernel

      [INPUT]
          Name              tail
          Tag               rke2
          Path              /var/lib/rancher/rke2/agent/logs/kubelet.log

      [INPUT]
          Name              tail
          Tag               rke2
          Path              /var/log/audit/audit.log

      [FILTER]
          Name              parser
          Match             *
          Key_Name          log
          Parser            klog
          Reserve_Data      On

      [FILTER]
          Name              parser
          Match             *
          Key_Name          MESSAGE
          Parser            klog
          Reserve_Data      On

      [FILTER]
          Name              parser
          Match             *
          Key_Name          MESSAGE
          Parser            rancher
          Reserve_Data      On

      [FILTER]
          Name              parser
          Match             *
          Key_Name          MESSAGE
          Parser            etcd
          Reserve_Data      On

      [OUTPUT]
          Name              forward
          Match             *
          Host              rancher-logging-root-fluentd.cattle-logging-system.svc
          Port              24240
          Retry_Limit       False
    parsers.conf: |
      [PARSER]
          Name              klog
          Format            regex
          Regex             ^(?<level>[IWEF])(?<timestamp>\d{4} \d{2}:\d{2}:\d{2}).\d{6} +?(?<thread_id>\d+) (?<filename>.+):(?<linenumber>\d+)] (?<message>.+)
          Time_Key          timestamp
          Time_Format       %m%d %T

      [PARSER]
          Name              rancher
          Format            regex
          Regex             ^time="(?<timestamp>.+)" level=(?<level>.+) msg="(?<msg>.+)"$
          Time_Key          timestamp
          Time_Format       %FT%H:%M:%S
      [PARSER]
          Name              etcd
          Format            json
          Time_Key          timestamp
          Time_Format       %FT%H:%M:%S.%L
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-logging
      meta.helm.sh/release-namespace: cattle-logging-system
    creationTimestamp: "2024-08-06T01:56:42Z"
    labels:
      app.kubernetes.io/instance: rancher-logging
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-logging
      app.kubernetes.io/version: 3.17.10
      helm.sh/chart: rancher-logging-103.0.0_up3.17.10
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:fluent-bit.conf: {}
          f:parsers.conf: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:42Z"
    name: rancher-logging-rke2
    namespace: cattle-logging-system
    resourceVersion: "6809"
    uid: bdc50a43-5050-42dd-92a4-f5277e6cbd2b
kind: List
metadata:
  resourceVersion: "770286"
