apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: KubeVirt
  metadata:
    annotations:
      helm.sh/resource-policy: keep
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2024-08-06T01:55:24Z"
    finalizers:
    - foregroundDeleteKubeVirt
    generation: 3
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubevirt
      app.kubernetes.io/part-of: kubevirt
      app.kubernetes.io/version: v1
      helm.sh/chart: kubevirt-0.1.0
      helm.sh/release: harvester
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:helm.sh/resource-policy: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:helm.sh/release: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          .: {}
          f:configuration:
            .: {}
            f:developerConfiguration:
              .: {}
              f:featureGates: {}
            f:emulatedMachines: {}
            f:network:
              .: {}
              f:defaultNetworkInterface: {}
              f:permitBridgeInterfaceOnPodNetwork: {}
              f:permitSlirpInterface: {}
          f:customizeComponents:
            .: {}
            f:patches: {}
          f:monitorAccount: {}
          f:monitorNamespace: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:55:24Z"
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:kubevirt.io/latest-observed-api-version: {}
            f:kubevirt.io/storage-observed-api-version: {}
          f:finalizers:
            .: {}
            v:"foregroundDeleteKubeVirt"null: {}
        f:spec:
          f:certificateRotateStrategy: {}
          f:workloadUpdateStrategy: {}
      manager: Go-http-client
      operation: Update
      time: "2024-08-06T01:56:18Z"
    - apiVersion: kubevirt.io/v1alpha3
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:configuration:
            f:permittedHostDevices:
              .: {}
              f:mediatedDevices: {}
      manager: Go-http-client
      operation: Update
      time: "2024-08-06T02:21:18Z"
    - apiVersion: kubevirt.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:generations: {}
          f:observedDeploymentConfig: {}
          f:observedDeploymentID: {}
          f:observedGeneration: {}
          f:observedKubeVirtRegistry: {}
          f:observedKubeVirtVersion: {}
          f:operatorVersion: {}
          f:outdatedVirtualMachineInstanceWorkloads: {}
          f:phase: {}
          f:targetDeploymentConfig: {}
          f:targetDeploymentID: {}
          f:targetKubeVirtRegistry: {}
          f:targetKubeVirtVersion: {}
      manager: Go-http-client
      operation: Update
      subresource: status
      time: "2024-08-06T02:21:35Z"
    name: kubevirt
    namespace: harvester-system
    resourceVersion: "36238"
    uid: e8fbfc77-713b-420b-a929-c51824f99a4f
  spec:
    certificateRotateStrategy: {}
    configuration:
      developerConfiguration:
        featureGates:
        - LiveMigration
        - HotplugVolumes
        - HostDevices
        - GPU
      emulatedMachines:
      - q35
      - pc-q35*
      - pc
      - pc-i440fx*
      network:
        defaultNetworkInterface: bridge
        permitBridgeInterfaceOnPodNetwork: true
        permitSlirpInterface: true
      permittedHostDevices:
        mediatedDevices:
        - externalResourceProvider: true
          mdevNameSelector: NVIDIA RTX5000-Ada-8Q
          resourceName: nvidia.com/NVIDIA_RTX5000-ADA-8Q
    customizeComponents:
      patches:
      - patch: '{"webhooks":[{"name":"kubevirt-validator.kubevirt.io","failurePolicy":"Ignore"},{"name":"kubevirt-update-validator.kubevirt.io","failurePolicy":"Ignore"}]}'
        resourceName: virt-operator-validator
        resourceType: ValidatingWebhookConfiguration
        type: strategic
      - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-api", "resources":{"limits":{"cpu":"400m","memory":"1100Mi"}}}]}}}}'
        resourceName: virt-api
        resourceType: Deployment
        type: strategic
      - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-controller",
          "resources":{"limits":{"cpu":"800m","memory":"1300Mi"}}}]}}}}'
        resourceName: virt-controller
        resourceType: Deployment
        type: strategic
      - patch: '{"spec":{"template":{"spec":{"containers":[{"name":"virt-handler",
          "resources":{"limits":{"cpu":"700m","memory":"1600Mi"}}}]}}}}'
        resourceName: virt-handler
        resourceType: DaemonSet
        type: strategic
    monitorAccount: rancher-monitoring-operator
    monitorNamespace: cattle-monitoring-system
    workloadUpdateStrategy: {}
  status:
    conditions:
    - lastProbeTime: "2024-08-06T02:21:35Z"
      lastTransitionTime: "2024-08-06T02:21:35Z"
      message: All components are ready.
      reason: AllComponentsReady
      status: "True"
      type: Available
    - lastProbeTime: "2024-08-06T02:21:35Z"
      lastTransitionTime: "2024-08-06T02:21:35Z"
      message: All components are ready.
      reason: AllComponentsReady
      status: "False"
      type: Progressing
    - lastProbeTime: "2024-08-06T02:21:35Z"
      lastTransitionTime: "2024-08-06T02:21:35Z"
      message: All components are ready.
      reason: AllComponentsReady
      status: "False"
      type: Degraded
    - lastProbeTime: "2024-08-06T01:57:29Z"
      lastTransitionTime: "null"
      message: All resources were created.
      reason: AllResourcesCreated
      status: "True"
      type: Created
    defaultArchitecture: amd64
    generations:
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstances.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancepresets.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancereplicasets.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachines.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancemigrations.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinesnapshots.snapshot.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinesnapshotcontents.snapshot.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinerestores.snapshot.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineinstancetypes.instancetype.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineclusterinstancetypes.instancetype.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinepools.pool.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: migrationpolicies.migrations.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachinepreferences.instancetype.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineclusterpreferences.instancetype.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineexports.export.kubevirt.io
      resource: customresourcedefinitions
    - group: apiextensions.k8s.io/v1
      lastGeneration: 1
      name: virtualmachineclones.clone.kubevirt.io
      resource: customresourcedefinitions
    - group: admissionregistration.k8s.io
      lastGeneration: 2
      name: virt-operator-validator
      resource: validatingwebhookconfigurations
    - group: admissionregistration.k8s.io
      lastGeneration: 2
      name: virt-api-validator
      resource: validatingwebhookconfigurations
    - group: admissionregistration.k8s.io
      lastGeneration: 2
      name: virt-api-mutator
      resource: mutatingwebhookconfigurations
    - group: apps
      lastGeneration: 5
      name: virt-api
      namespace: harvester-system
      resource: deployments
    - group: apps
      lastGeneration: 4
      name: virt-controller
      namespace: harvester-system
      resource: deployments
    - group: apps
      lastGeneration: 1
      name: virt-controller-pdb
      namespace: harvester-system
      resource: poddisruptionbudgets
    - group: apps
      lastGeneration: 1
      name: virt-handler
      namespace: harvester-system
      resource: daemonsets
    - group: apps
      lastGeneration: 1
      name: virt-api-pdb
      namespace: harvester-system
      resource: poddisruptionbudgets
    observedDeploymentConfig: '{"id":"8c5c8323ebf23c689ce9bc87a13132d3fae18c7a","namespace":"harvester-system","registry":"registry.suse.com/suse/sles/15.5","kubeVirtVersion":"1.1.1-150500.8.15.1","virtOperatorImage":"registry.suse.com/suse/sles/15.5/virt-operator:1.1.1-150500.8.15.1","additionalProperties":{"CertificateRotationStrategy":"\u003cv1.KubeVirtCertificateRotateStrategy
      Value\u003e","Configuration":"\u003cv1.KubeVirtConfiguration Value\u003e","CustomizeComponents":"\u003cv1.CustomizeComponents
      Value\u003e","ImagePullPolicy":"","ImagePullSecrets":"null","Infra":"\u003c*v1.ComponentConfig
      Value\u003e","MonitorAccount":"rancher-monitoring-operator","MonitorNamespace":"cattle-monitoring-system","ProductComponent":"","ProductName":"","ProductVersion":"","ServiceMonitorNamespace":"","UninstallStrategy":"","WorkloadUpdateStrategy":"\u003cv1.KubeVirtWorkloadUpdateStrategy
      Value\u003e","Workloads":"\u003c*v1.ComponentConfig Value\u003e"}}'
    observedDeploymentID: 8c5c8323ebf23c689ce9bc87a13132d3fae18c7a
    observedGeneration: 3
    observedKubeVirtRegistry: registry.suse.com/suse/sles/15.5
    observedKubeVirtVersion: 1.1.1-150500.8.15.1
    operatorVersion: v1.1.1
    outdatedVirtualMachineInstanceWorkloads: 0
    phase: Deployed
    targetDeploymentConfig: '{"id":"8c5c8323ebf23c689ce9bc87a13132d3fae18c7a","namespace":"harvester-system","registry":"registry.suse.com/suse/sles/15.5","kubeVirtVersion":"1.1.1-150500.8.15.1","virtOperatorImage":"registry.suse.com/suse/sles/15.5/virt-operator:1.1.1-150500.8.15.1","additionalProperties":{"CertificateRotationStrategy":"\u003cv1.KubeVirtCertificateRotateStrategy
      Value\u003e","Configuration":"\u003cv1.KubeVirtConfiguration Value\u003e","CustomizeComponents":"\u003cv1.CustomizeComponents
      Value\u003e","ImagePullPolicy":"","ImagePullSecrets":"null","Infra":"\u003c*v1.ComponentConfig
      Value\u003e","MonitorAccount":"rancher-monitoring-operator","MonitorNamespace":"cattle-monitoring-system","ProductComponent":"","ProductName":"","ProductVersion":"","ServiceMonitorNamespace":"","UninstallStrategy":"","WorkloadUpdateStrategy":"\u003cv1.KubeVirtWorkloadUpdateStrategy
      Value\u003e","Workloads":"\u003c*v1.ComponentConfig Value\u003e"}}'
    targetDeploymentID: 8c5c8323ebf23c689ce9bc87a13132d3fae18c7a
    targetKubeVirtRegistry: registry.suse.com/suse/sles/15.5
    targetKubeVirtVersion: 1.1.1-150500.8.15.1
kind: List
metadata:
  continue: "null"
  resourceVersion: "770255"
