apiVersion: v1
items:
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2024-08-06T01:55:54Z"
    managedFields:
    - apiVersion: coordination.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:acquireTime: {}
          f:holderIdentity: {}
          f:leaseDurationSeconds: {}
          f:leaseTransitions: {}
          f:renewTime: {}
      manager: csi-provisioner
      operation: Update
      time: "2024-08-06T14:12:14Z"
    name: driver-longhorn-io
    namespace: longhorn-system
    resourceVersion: "770188"
    uid: 51cbb619-39a1-4fe3-862c-a5339b2e246e
  spec:
    acquireTime: "2024-08-06T01:55:54.854132Z"
    holderIdentity: 1722909354852-282-driver-longhorn-io
    leaseDurationSeconds: 15
    leaseTransitions: 0
    renewTime: "2024-08-06T14:12:14.547567Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2024-08-06T01:55:54Z"
    managedFields:
    - apiVersion: coordination.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:acquireTime: {}
          f:holderIdentity: {}
          f:leaseDurationSeconds: {}
          f:leaseTransitions: {}
          f:renewTime: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T14:12:18Z"
    name: external-attacher-leader-driver-longhorn-io
    namespace: longhorn-system
    resourceVersion: "770270"
    uid: 8a06e31b-094b-41ab-90d1-c35fb7dea3ca
  spec:
    acquireTime: "2024-08-06T01:55:54.842477Z"
    holderIdentity: csi-attacher-5fbd66cf8-5fn4n
    leaseDurationSeconds: 15
    leaseTransitions: 0
    renewTime: "2024-08-06T14:12:18.890320Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2024-08-06T01:55:54Z"
    managedFields:
    - apiVersion: coordination.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:acquireTime: {}
          f:holderIdentity: {}
          f:leaseDurationSeconds: {}
          f:leaseTransitions: {}
          f:renewTime: {}
      manager: csi-resizer
      operation: Update
      time: "2024-08-06T14:12:14Z"
    name: external-resizer-driver-longhorn-io
    namespace: longhorn-system
    resourceVersion: "770203"
    uid: 8e29299d-511f-4368-bc61-110a809ca5c1
  spec:
    acquireTime: "2024-08-06T01:55:54.822467Z"
    holderIdentity: csi-resizer-74c5555748-5vrxw
    leaseDurationSeconds: 15
    leaseTransitions: 0
    renewTime: "2024-08-06T14:12:14.944479Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2024-08-06T01:55:54Z"
    managedFields:
    - apiVersion: coordination.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:acquireTime: {}
          f:holderIdentity: {}
          f:leaseDurationSeconds: {}
          f:leaseTransitions: {}
          f:renewTime: {}
      manager: csi-snapshotter
      operation: Update
      time: "2024-08-06T14:12:14Z"
    name: external-snapshotter-leader-driver-longhorn-io
    namespace: longhorn-system
    resourceVersion: "770187"
    uid: 980aee6d-bf5f-42e8-83ec-95480c6dda1a
  spec:
    acquireTime: "2024-08-06T01:55:54.849936Z"
    holderIdentity: csi-snapshotter-6bc4bcf4c5-g9p76
    leaseDurationSeconds: 15
    leaseTransitions: 0
    renewTime: "2024-08-06T14:12:14.407159Z"
- apiVersion: coordination.k8s.io/v1
  kind: Lease
  metadata:
    creationTimestamp: "2024-08-06T01:55:47Z"
    managedFields:
    - apiVersion: coordination.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:acquireTime: {}
          f:holderIdentity: {}
          f:leaseDurationSeconds: {}
          f:leaseTransitions: {}
          f:renewTime: {}
      manager: longhorn-manager
      operation: Update
      time: "2024-08-06T01:55:47Z"
    name: longhorn-manager-upgrade-lock
    namespace: longhorn-system
    resourceVersion: "5084"
    uid: a390dc5d-446e-499e-ba15-9dba54bba36b
  spec:
    acquireTime: "2024-08-06T01:55:47.687934Z"
    holderIdentity: "null"
    leaseDurationSeconds: 1
    leaseTransitions: 0
    renewTime: "2024-08-06T01:55:47.687934Z"
kind: List
metadata:
  resourceVersion: "770272"
