apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2024-08-06T01:52:48Z"
    name: default
    namespace: cattle-fleet-clusters-system
    resourceVersion: "1690"
    uid: f6bb2d44-fb7f-4c3d-a66c-84b0530e8209
kind: List
metadata:
  resourceVersion: "770219"
