apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-monitoring
      meta.helm.sh/release-namespace: cattle-monitoring-system
    creationTimestamp: "2024-08-06T01:56:59Z"
    generation: 1
    labels:
      app: rancher-monitoring-prometheus
      app.kubernetes.io/instance: rancher-monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: rancher-monitoring
      app.kubernetes.io/version: 103.0.3_up45.31.1
      chart: rancher-monitoring-103.0.3_up45.31.1
      heritage: Helm
      release: rancher-monitoring
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
        f:spec:
          .: {}
          f:alerting:
            .: {}
            f:alertmanagers: {}
          f:containers: {}
          f:enableAdminAPI: {}
          f:evaluationInterval: {}
          f:externalUrl: {}
          f:hostNetwork: {}
          f:image: {}
          f:listenLocal: {}
          f:logFormat: {}
          f:logLevel: {}
          f:nodeSelector:
            .: {}
            f:kubernetes.io/os: {}
          f:paused: {}
          f:podMonitorNamespaceSelector: {}
          f:podMonitorSelector: {}
          f:portName: {}
          f:probeNamespaceSelector: {}
          f:probeSelector: {}
          f:replicas: {}
          f:resources:
            .: {}
            f:limits:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:requests:
              .: {}
              f:cpu: {}
              f:memory: {}
          f:retention: {}
          f:retentionSize: {}
          f:routePrefix: {}
          f:ruleNamespaceSelector: {}
          f:ruleSelector: {}
          f:scrapeInterval: {}
          f:securityContext:
            .: {}
            f:fsGroup: {}
            f:runAsGroup: {}
            f:runAsNonRoot: {}
            f:runAsUser: {}
          f:serviceAccountName: {}
          f:serviceMonitorNamespaceSelector: {}
          f:serviceMonitorSelector: {}
          f:shards: {}
          f:storage:
            .: {}
            f:volumeClaimTemplate:
              .: {}
              f:spec:
                .: {}
                f:accessModes: {}
                f:resources:
                  .: {}
                  f:requests:
                    .: {}
                    f:storage: {}
                f:storageClassName: {}
                f:volumeMode: {}
          f:tolerations: {}
          f:tsdb:
            .: {}
            f:outOfOrderTimeWindow: {}
          f:version: {}
          f:volumes: {}
          f:walCompression: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:59Z"
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:observedGeneration: {}
              f:status: {}
              f:type: {}
            k:{"type":"Reconciled"}:
              .: {}
              f:lastTransitionTime: {}
              f:observedGeneration: {}
              f:status: {}
              f:type: {}
          f:paused: {}
          f:replicas: {}
          f:shardStatuses:
            .: {}
            k:{"shardID":"0"}:
              .: {}
              f:availableReplicas: {}
              f:replicas: {}
              f:shardID: {}
              f:unavailableReplicas: {}
              f:updatedReplicas: {}
          f:unavailableReplicas: {}
          f:updatedReplicas: {}
      manager: PrometheusOperator
      operation: Update
      subresource: status
      time: "2024-08-06T14:09:08Z"
    name: rancher-monitoring-prometheus
    namespace: cattle-monitoring-system
    resourceVersion: "767042"
    uid: 586d1b69-c991-4a35-b61e-a9a0be9bf1f5
  spec:
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: rancher-monitoring-alertmanager
        namespace: cattle-monitoring-system
        pathPrefix: /
        port: http-web
    containers:
    - args:
      - nginx
      - -g
      - daemon off;
      - -c
      - /nginx/nginx.conf
      image: rancher/mirrored-library-nginx:1.24.0-alpine
      name: prometheus-proxy
      ports:
      - containerPort: 8081
        name: nginx-http
        protocol: TCP
      securityContext:
        runAsGroup: 101
        runAsUser: 101
      volumeMounts:
      - mountPath: /nginx
        name: prometheus-nginx
      - mountPath: /var/cache/nginx
        name: nginx-home
    enableAdminAPI: false
    evaluationInterval: 1m
    externalUrl: https://10.10.110.100/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/
    hostNetwork: false
    image: docker.io/rancher/mirrored-prometheus-prometheus:v2.42.0
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    nodeSelector:
      kubernetes.io/os: linux
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    portName: http-web
    probeNamespaceSelector: {}
    probeSelector:
      matchLabels:
        release: rancher-monitoring
    replicas: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2500Mi
      requests:
        cpu: 750m
        memory: 1750Mi
    retention: 5d
    retentionSize: 50GiB
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector: {}
    scrapeInterval: 1m
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: rancher-monitoring-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    shards: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: harvester-longhorn
          volumeMode: Filesystem
    tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    tsdb:
      outOfOrderTimeWindow: 0s
    version: v2.42.0
    volumes:
    - emptyDir: {}
      name: nginx-home
    - configMap:
        defaultMode: 438
        name: prometheus-nginx-proxy-config
      name: prometheus-nginx
    walCompression: true
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-08-06T14:09:08Z"
      observedGeneration: 1
      status: "True"
      type: Available
    - lastTransitionTime: "2024-08-06T14:09:08Z"
      observedGeneration: 1
      status: "True"
      type: Reconciled
    paused: false
    replicas: 1
    shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  continue: "null"
  resourceVersion: "770238"
