apiVersion: v1
items:
- apiVersion: node.harvesterhci.io/v1beta1
  kind: Ksmtuned
  metadata:
    creationTimestamp: "2024-08-06T01:55:47Z"
    finalizers:
    - wrangler.cattle.io/harvester-ksmtuned-handler
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-ksmtuned-handler"null: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"9b6fb3e0-6ead-4e4f-bb03-9bc72f605557"}: {}
        f:spec:
          .: {}
          f:ksmtunedParameters:
            .: {}
            f:boost: {}
            f:decay: {}
            f:maxPages: {}
            f:minPages: {}
            f:sleepMsec: {}
          f:mergeAcrossNodes: {}
          f:mode: {}
          f:run: {}
          f:thresCoef: {}
      manager: harvester-node-manager
      operation: Update
      time: "2024-08-06T01:55:47Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:fullScans: {}
          f:ksmdPhase: {}
          f:shared: {}
          f:sharing: {}
          f:stableNodeChains: {}
          f:stableNodeDups: {}
          f:unshared: {}
          f:volatile: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2024-08-06T01:56:46Z"
    name: harvesterdev1
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: harvesterdev1
      uid: 9b6fb3e0-6ead-4e4f-bb03-9bc72f605557
    resourceVersion: "7152"
    uid: eaa25a4c-7371-446b-8fb0-b2d891cdda57
  spec:
    ksmtunedParameters:
      boost: 0
      decay: 0
      maxPages: 100
      minPages: 100
      sleepMsec: 20
    mergeAcrossNodes: 0
    mode: standard
    run: stop
    thresCoef: 20
  status:
    fullScans: 0
    ksmdPhase: Stopped
    shared: 0
    sharing: 0
    stableNodeChains: 0
    stableNodeDups: 0
    unshared: 0
    volatile: 0
- apiVersion: node.harvesterhci.io/v1beta1
  kind: Ksmtuned
  metadata:
    creationTimestamp: "2024-08-06T02:11:49Z"
    finalizers:
    - wrangler.cattle.io/harvester-ksmtuned-handler
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-ksmtuned-handler"null: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"141de37b-4cad-4b6f-9831-ffeed49d0658"}: {}
        f:spec:
          .: {}
          f:ksmtunedParameters:
            .: {}
            f:boost: {}
            f:decay: {}
            f:maxPages: {}
            f:minPages: {}
            f:sleepMsec: {}
          f:mergeAcrossNodes: {}
          f:mode: {}
          f:run: {}
          f:thresCoef: {}
      manager: harvester-node-manager
      operation: Update
      time: "2024-08-06T02:11:49Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:fullScans: {}
          f:ksmdPhase: {}
          f:shared: {}
          f:sharing: {}
          f:stableNodeChains: {}
          f:stableNodeDups: {}
          f:unshared: {}
          f:volatile: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2024-08-06T02:12:45Z"
    name: harvesterdev2
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: harvesterdev2
      uid: 141de37b-4cad-4b6f-9831-ffeed49d0658
    resourceVersion: "25123"
    uid: c192ecbe-2eea-4649-a4bb-61047926f6c6
  spec:
    ksmtunedParameters:
      boost: 0
      decay: 0
      maxPages: 100
      minPages: 100
      sleepMsec: 20
    mergeAcrossNodes: 0
    mode: standard
    run: stop
    thresCoef: 20
  status:
    fullScans: 0
    ksmdPhase: Stopped
    shared: 0
    sharing: 0
    stableNodeChains: 0
    stableNodeDups: 0
    unshared: 0
    volatile: 0
- apiVersion: node.harvesterhci.io/v1beta1
  kind: Ksmtuned
  metadata:
    creationTimestamp: "2024-08-06T02:13:35Z"
    finalizers:
    - wrangler.cattle.io/harvester-ksmtuned-handler
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-ksmtuned-handler"null: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"450a2bb5-9551-4e4f-aa7a-6a8a583bbef8"}: {}
        f:spec:
          .: {}
          f:ksmtunedParameters:
            .: {}
            f:boost: {}
            f:decay: {}
            f:maxPages: {}
            f:minPages: {}
            f:sleepMsec: {}
          f:mergeAcrossNodes: {}
          f:mode: {}
          f:run: {}
          f:thresCoef: {}
      manager: harvester-node-manager
      operation: Update
      time: "2024-08-06T02:13:35Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:fullScans: {}
          f:ksmdPhase: {}
          f:shared: {}
          f:sharing: {}
          f:stableNodeChains: {}
          f:stableNodeDups: {}
          f:unshared: {}
          f:volatile: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2024-08-06T02:14:32Z"
    name: harvesterdev3
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: harvesterdev3
      uid: 450a2bb5-9551-4e4f-aa7a-6a8a583bbef8
    resourceVersion: "28211"
    uid: b4506dc4-5330-47a7-8274-67dbd1a5ae62
  spec:
    ksmtunedParameters:
      boost: 0
      decay: 0
      maxPages: 100
      minPages: 100
      sleepMsec: 20
    mergeAcrossNodes: 0
    mode: standard
    run: stop
    thresCoef: 20
  status:
    fullScans: 0
    ksmdPhase: Stopped
    shared: 0
    sharing: 0
    stableNodeChains: 0
    stableNodeDups: 0
    unshared: 0
    volatile: 0
- apiVersion: node.harvesterhci.io/v1beta1
  kind: Ksmtuned
  metadata:
    creationTimestamp: "2024-08-06T02:16:06Z"
    finalizers:
    - wrangler.cattle.io/harvester-ksmtuned-handler
    generation: 1
    managedFields:
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/harvester-ksmtuned-handler"null: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"cb77b855-ef85-4af4-b07c-b9963a49007b"}: {}
        f:spec:
          .: {}
          f:ksmtunedParameters:
            .: {}
            f:boost: {}
            f:decay: {}
            f:maxPages: {}
            f:minPages: {}
            f:sleepMsec: {}
          f:mergeAcrossNodes: {}
          f:mode: {}
          f:run: {}
          f:thresCoef: {}
      manager: harvester-node-manager
      operation: Update
      time: "2024-08-06T02:16:06Z"
    - apiVersion: node.harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:fullScans: {}
          f:ksmdPhase: {}
          f:shared: {}
          f:sharing: {}
          f:stableNodeChains: {}
          f:stableNodeDups: {}
          f:unshared: {}
          f:volatile: {}
      manager: harvester-node-manager
      operation: Update
      subresource: status
      time: "2024-08-06T02:17:02Z"
    name: harvesterdev7
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: harvesterdev7
      uid: cb77b855-ef85-4af4-b07c-b9963a49007b
    resourceVersion: "31499"
    uid: 88e8f36c-0a89-49eb-bba9-5f4745466530
  spec:
    ksmtunedParameters:
      boost: 0
      decay: 0
      maxPages: 100
      minPages: 100
      sleepMsec: 20
    mergeAcrossNodes: 0
    mode: standard
    run: stop
    thresCoef: 20
  status:
    fullScans: 0
    ksmdPhase: Stopped
    shared: 0
    sharing: 0
    stableNodeChains: 0
    stableNodeDups: 0
    unshared: 0
    volatile: 0
kind: List
metadata:
  continue: "null"
  resourceVersion: "770167"
