apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/containerID: 6dd2ed51972166aaaa54915d2a4f0f049dc88e65b2b9ce12de89eb9c82353f78
      cni.projectcalico.org/podIP: 10.52.1.28/32
      cni.projectcalico.org/podIPs: 10.52.1.28/32
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "k8s-pod-network",
            "ips": [
                "10.52.1.28"
            ],
            "default": true,
            "dns": {}
        }]
    creationTimestamp: "2024-08-06T02:14:20Z"
    generateName: fleet-agent-6d5df7d9cd-
    labels:
      app: fleet-agent
      pod-template-hash: 6d5df7d9cd
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"4f9182a6-045b-42de-8efe-e25c6481066f"}: {}
        f:spec:
          f:affinity:
            .: {}
            f:nodeAffinity:
              .: {}
              f:preferredDuringSchedulingIgnoredDuringExecution: {}
          f:containers:
            k:{"name":"fleet-agent"}:
              .: {}
              f:env:
                .: {}
                k:{"name":"AGENT_SCOPE"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"CHECKIN_INTERVAL"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"NAMESPACE"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:fieldRef: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:nodeSelector: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext:
            .: {}
            f:runAsGroup: {}
            f:runAsNonRoot: {}
            f:runAsUser: {}
          f:serviceAccount: {}
          f:serviceAccountName: {}
          f:terminationGracePeriodSeconds: {}
          f:tolerations: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:14:20Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:cni.projectcalico.org/containerID: {}
            f:cni.projectcalico.org/podIP: {}
            f:cni.projectcalico.org/podIPs: {}
      manager: calico
      operation: Update
      subresource: status
      time: "2024-08-06T02:14:21Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.52.1.28"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      subresource: status
      time: "2024-08-06T02:14:21Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:k8s.v1.cni.cncf.io/network-status: {}
      manager: multus
      operation: Update
      subresource: status
      time: "2024-08-06T02:14:21Z"
    name: fleet-agent-6d5df7d9cd-5897v
    namespace: cattle-fleet-local-system
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: fleet-agent-6d5df7d9cd
      uid: 4f9182a6-045b-42de-8efe-e25c6481066f
    resourceVersion: "28025"
    uid: bc9658d7-b530-4271-aec1-30b2f4f3dbf1
  spec:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: fleet.cattle.io/agent
              operator: In
              values:
              - "true"
          weight: 1
    containers:
    - env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.namespace
      - name: AGENT_SCOPE
        value: cattle-fleet-local-system
      - name: CHECKIN_INTERVAL
        value: 15m0s
      image: rancher/fleet-agent:v0.9.2
      imagePullPolicy: IfNotPresent
      name: fleet-agent
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-cq6xm
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: harvesterdev2
    nodeSelector:
      kubernetes.io/os: linux
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccount: fleet-agent
    serviceAccountName: fleet-agent
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoSchedule
      key: node.cloudprovider.kubernetes.io/uninitialized
      operator: Equal
      value: "true"
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-cq6xm
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: "null"
      lastTransitionTime: "2024-08-06T02:14:20Z"
      status: "True"
      type: Initialized
    - lastProbeTime: "null"
      lastTransitionTime: "2024-08-06T02:14:21Z"
      status: "True"
      type: Ready
    - lastProbeTime: "null"
      lastTransitionTime: "2024-08-06T02:14:21Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: "null"
      lastTransitionTime: "2024-08-06T02:14:20Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://ffb008746df3d5f2272980d479be5bc8b24a896c55d980f552428485b1a55767
      image: docker.io/rancher/fleet-agent:v0.9.2
      imageID: sha256:764c59641b7c2d015321ff486eb747d7e098c1d555217c03c3298c96e1545442
      lastState: {}
      name: fleet-agent
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-08-06T02:14:21Z"
    hostIP: 10.10.110.71
    phase: Running
    podIP: 10.52.1.28
    podIPs:
    - ip: 10.52.1.28
    qosClass: BestEffort
    startTime: "2024-08-06T02:14:20Z"
kind: List
metadata:
  resourceVersion: "770217"
