apiVersion: v1
items:
- apiVersion: logging-extensions.banzaicloud.io/v1alpha1
  kind: EventTailer
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-logging
      meta.helm.sh/release-namespace: cattle-logging-system
    creationTimestamp: "2024-08-06T01:56:42Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: logging-extensions.banzaicloud.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:spec:
          .: {}
          f:controlNamespace: {}
          f:workloadOverrides:
            .: {}
            f:containers: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:42Z"
    name: harvester-default
    resourceVersion: "6824"
    uid: 9792d8a9-22da-4d39-9df8-a458a0ed046f
  spec:
    controlNamespace: cattle-logging-system
    workloadOverrides:
      containers:
      - image: rancher/harvester-eventrouter:v0.2.0
        name: event-tailer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 20Mi
kind: List
metadata:
  continue: "null"
  resourceVersion: "770167"
