apiVersion: v1
items:
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/5ySQY/TMBCF/wqas1OSNs0mljgte9oDqEJcEIeJPd6auHZkT4pQlf+OHBZt6bLVao9x3vN7841PcCBGjYwgT4DeB0a2waf8GfofpDgRr6INK4XMjlY2vLcaJMSBCuWmxBRBvCgNPz3F4uE4gIQxhqNNNnjrH84kx0q8u7def7h95W0eDwQSXFDoXiVOI6rsMI6Iiz++WYCKtMz6xR4oMR5GkH5yToDDntxVAntMe5BQlW3T9G3fb+q+o4ZUua43plRt2TVK96irTlNz0+W0i9Yv9RKw9N6RoUheUQL57QQ42q8UM7trHEFA74IaPuUbPpIjXgwcJxKggucYnKP492SwPi/yCftFxWnZ83ZzUxq92RaVaamom3ZdtGXZFE2tqnJbm7pbb2H+PgtII6kM7THps0NPd16PwXrO5/uQGCSAgDFEBlnO4h/tjszyCM9njQNdjvhYe3d/d3tmfl7/yuatNxETx0nxFN+Q+39ic2bAyFO6pLAj1L9AGnSJnqc//Zvn3wEAAP//mHg+upADAAA
      objectset.rio.cattle.io/id: rke-cluster
      objectset.rio.cattle.io/owner-gvk: provisioning.cattle.io/v1, Kind=Cluster
      objectset.rio.cattle.io/owner-name: local
      objectset.rio.cattle.io/owner-namespace: fleet-local
    creationTimestamp: "2024-08-06T01:54:05Z"
    finalizers:
    - cluster.cluster.x-k8s.io
    generation: 288
    labels:
      objectset.rio.cattle.io/hash: 10866b8bb34b9e6ec0243f0c8096cdbad19de679
    managedFields:
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"cluster.cluster.x-k8s.io"null: {}
        f:spec:
          f:controlPlaneEndpoint:
            f:host: {}
            f:port: {}
      manager: manager
      operation: Update
      time: "2024-08-06T14:07:00Z"
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:controlPlaneReady: {}
          f:infrastructureReady: {}
          f:observedGeneration: {}
          f:phase: {}
      manager: manager
      operation: Update
      subresource: status
      time: "2024-08-06T14:07:00Z"
    - apiVersion: cluster.x-k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"5370fd35-1f8e-4682-8006-64c1054f4925"}: {}
        f:spec:
          .: {}
          f:controlPlaneEndpoint: {}
          f:controlPlaneRef: {}
          f:infrastructureRef: {}
      manager: rancher
      operation: Update
      time: "2024-08-06T14:07:00Z"
    name: local
    namespace: fleet-local
    ownerReferences:
    - apiVersion: provisioning.cattle.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Cluster
      name: local
      uid: 5370fd35-1f8e-4682-8006-64c1054f4925
    resourceVersion: "764783"
    uid: 2d7e76f9-bc59-40c5-bca5-5f107c5c834e
  spec:
    controlPlaneEndpoint:
      host: localhost
      port: 6443
    controlPlaneRef:
      apiVersion: rke.cattle.io/v1
      kind: RKEControlPlane
      name: local
      namespace: fleet-local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: RKECluster
      name: local
      namespace: fleet-local
  status:
    conditions:
    - lastTransitionTime: "2024-08-06T01:54:06Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2024-08-06T01:57:44Z"
      status: "True"
      type: ControlPlaneInitialized
    - lastTransitionTime: "2024-08-06T02:25:00Z"
      status: "True"
      type: ControlPlaneReady
    - lastTransitionTime: "2024-08-06T01:54:06Z"
      status: "True"
      type: InfrastructureReady
    controlPlaneReady: true
    infrastructureReady: true
    observedGeneration: 288
    phase: Provisioned
kind: List
metadata:
  continue: "null"
  resourceVersion: "770249"
