apiVersion: v1
items:
- apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"helm.cattle.io/v1","kind":"HelmChartConfig","metadata":{"annotations":{},"name":"rke2-ingress-nginx","namespace":"kube-system"},"spec":{"valuesContent":"controller:\n  config:\n    proxy-body-size: \"0\"\n    proxy-request-buffering: \"off\"\n  admissionWebhooks:\n    port: 8444\n  publishService:\n    pathOverride: kube-system/ingress-expose\n  extraArgs:\n    default-ssl-certificate: cattle-system/tls-rancher-internal"}}
    creationTimestamp: "2024-08-06T01:53:30Z"
    generation: 2
    managedFields:
    - apiVersion: helm.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2024-08-06T01:53:30Z"
    - apiVersion: helm.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:valuesContent: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T01:56:40Z"
    name: rke2-ingress-nginx
    namespace: kube-system
    resourceVersion: "6424"
    uid: f7e0778b-249a-44ac-ba2a-73abf6a859b3
  spec:
    valuesContent: |
      controller:
          admissionWebhooks:
              port: 8444
          config:
              proxy-body-size: "0"
              proxy-request-buffering: "off"
          extraArgs:
              default-ssl-certificate: cattle-system/tls-rancher-internal
          publishService:
              pathOverride: kube-system/ingress-expose
kind: List
metadata:
  continue: "null"
  resourceVersion: "770192"
