apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      harvesterhci.io/imageId: default/image-nntjr
      harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/gpu"]}]'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2024-08-06T13:39:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/imageId: {}
            f:harvesterhci.io/owned-by: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T13:39:34Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T13:39:36Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2024-08-06T13:39:36Z"
    name: gpu-disk-0-losvf
    namespace: default
    resourceVersion: "736718"
    uid: 865168f6-f0e4-440b-9d85-5729a45b1445
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    storageClassName: longhorn-image-nntjr
    volumeMode: Block
    volumeName: pvc-865168f6-f0e4-440b-9d85-5729a45b1445
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 40Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/gpu"]}]'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2024-08-06T13:39:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:harvesterhci.io/owned-by: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T13:39:34Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T13:39:36Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2024-08-06T13:39:36Z"
    name: gpu-disk-1-kfxss
    namespace: default
    resourceVersion: "736726"
    uid: cfe1ee5d-630f-47d5-9585-8282eb4d31fb
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    storageClassName: harvester-longhorn
    volumeMode: Block
    volumeName: pvc-cfe1ee5d-630f-47d5-9585-8282eb4d31fb
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 40Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      harvesterhci.io/imageId: default/image-qwfqg
      harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/gputest-gpu1-1df5240c-87trc"]}]'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2024-08-06T14:09:05Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/imageId: {}
            f:harvesterhci.io/owned-by: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T14:09:05Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T14:09:07Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2024-08-06T14:09:07Z"
    name: gputest-gpu1-1df5240c-87trc-disk-0-k6q7q
    namespace: default
    resourceVersion: "767026"
    uid: 6900257a-3f92-48a9-8c07-4928c79b253f
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    storageClassName: longhorn-image-qwfqg
    volumeMode: Block
    volumeName: pvc-6900257a-3f92-48a9-8c07-4928c79b253f
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 40Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      harvesterhci.io/imageId: default/image-qwfqg
      harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/gputest-primary-c31607d4-fqgjd"]}]'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2024-08-06T02:24:15Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/imageId: {}
            f:harvesterhci.io/owned-by: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T02:24:16Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:24:17Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2024-08-06T02:24:17Z"
    name: gputest-primary-c31607d4-fqgjd-disk-0-4xtb4
    namespace: default
    resourceVersion: "39237"
    uid: 5086a1f6-bff9-4b02-a41d-cd9bac5005a6
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    storageClassName: longhorn-image-qwfqg
    volumeMode: Block
    volumeName: pvc-5086a1f6-bff9-4b02-a41d-cd9bac5005a6
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 40Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      harvesterhci.io/imageId: default/image-qwfqg
      harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/gputest-primary-c31607d4-hpllh"]}]'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2024-08-06T02:24:06Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/imageId: {}
            f:harvesterhci.io/owned-by: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T02:24:07Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:24:09Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2024-08-06T02:24:09Z"
    name: gputest-primary-c31607d4-hpllh-disk-0-9xgqk
    namespace: default
    resourceVersion: "38796"
    uid: 19d9e182-85db-4649-a1d3-ff4d85d00bbb
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    storageClassName: longhorn-image-qwfqg
    volumeMode: Block
    volumeName: pvc-19d9e182-85db-4649-a1d3-ff4d85d00bbb
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 40Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      harvesterhci.io/imageId: default/image-qwfqg
      harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/gputest-primary-c31607d4-nr27s"]}]'
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
      volume.kubernetes.io/storage-provisioner: driver.longhorn.io
    creationTimestamp: "2024-08-06T02:24:13Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:harvesterhci.io/imageId: {}
            f:harvesterhci.io/owned-by: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T02:24:14Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
            f:volume.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:24:16Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2024-08-06T02:24:16Z"
    name: gputest-primary-c31607d4-nr27s-disk-0-rlg2q
    namespace: default
    resourceVersion: "39098"
    uid: 928d5ddc-47de-4481-9c34-abd84a3c9164
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    storageClassName: longhorn-image-qwfqg
    volumeMode: Block
    volumeName: pvc-928d5ddc-47de-4481-9c34-abd84a3c9164
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 40Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: "770184"
