apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    annotations:
      driver.longhorn.io/git-commit: dcd5164185d7130732f72bb2e978dfdc0338acd1
      driver.longhorn.io/version: v1.6.2
    creationTimestamp: "2024-08-06T01:55:52Z"
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:driver.longhorn.io/git-commit: {}
            f:driver.longhorn.io/version: {}
        f:spec:
          f:attachRequired: {}
          f:fsGroupPolicy: {}
          f:podInfoOnMount: {}
          f:requiresRepublish: {}
          f:storageCapacity: {}
          f:volumeLifecycleModes:
            .: {}
            v:"Persistent"null: {}
      manager: longhorn-manager
      operation: Update
      time: "2024-08-06T01:55:52Z"
    name: driver.longhorn.io
    resourceVersion: "5256"
    uid: 774479e0-3527-4f8e-bdaf-139fcd846bc9
  spec:
    attachRequired: true
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: true
    requiresRepublish: false
    storageCapacity: false
    volumeLifecycleModes:
    - Persistent
kind: List
metadata:
  resourceVersion: "770146"
