apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    annotations:
      csi.alpha.kubernetes.io/node-id: harvesterdev7
    creationTimestamp: "2024-08-06T02:24:11Z"
    finalizers:
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:csi.alpha.kubernetes.io/node-id: {}
          f:finalizers:
            .: {}
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T02:24:11Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attacher: {}
          f:nodeName: {}
          f:source:
            f:persistentVolumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:24:11Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:attached: {}
      manager: csi-attacher
      operation: Update
      subresource: status
      time: "2024-08-06T02:24:33Z"
    name: csi-26ef716f65f2182b1448aa8c447d211e0e00e9b8345dcd47cda5665c16c49c29
    resourceVersion: "39656"
    uid: 7824d1b7-f1e3-44f6-9b73-696df4726057
  spec:
    attacher: driver.longhorn.io
    nodeName: harvesterdev7
    source:
      persistentVolumeName: pvc-19d9e182-85db-4649-a1d3-ff4d85d00bbb
  status:
    attached: true
- apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    annotations:
      csi.alpha.kubernetes.io/node-id: harvesterdev2
    creationTimestamp: "2024-08-06T02:24:19Z"
    finalizers:
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:csi.alpha.kubernetes.io/node-id: {}
          f:finalizers:
            .: {}
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T02:24:19Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attacher: {}
          f:nodeName: {}
          f:source:
            f:persistentVolumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:24:19Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:attached: {}
      manager: csi-attacher
      operation: Update
      subresource: status
      time: "2024-08-06T02:24:33Z"
    name: csi-5b8da95e44899a4d699b15b38a7737b8e58fc38c50178af97313a2244b43c190
    resourceVersion: "39658"
    uid: 97f05ff9-7260-4578-b856-3fa1bfd6787c
  spec:
    attacher: driver.longhorn.io
    nodeName: harvesterdev2
    source:
      persistentVolumeName: pvc-5086a1f6-bff9-4b02-a41d-cd9bac5005a6
  status:
    attached: true
- apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    annotations:
      csi.alpha.kubernetes.io/node-id: harvesterdev1
    creationTimestamp: "2024-08-06T01:57:07Z"
    finalizers:
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:csi.alpha.kubernetes.io/node-id: {}
          f:finalizers:
            .: {}
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T01:57:07Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attacher: {}
          f:nodeName: {}
          f:source:
            f:persistentVolumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:57:07Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:attached: {}
      manager: csi-attacher
      operation: Update
      subresource: status
      time: "2024-08-06T01:57:17Z"
    name: csi-93766c6ac1aafb1db35bf2f53f177b1c70ae60a064124313bd304be22d329cbb
    resourceVersion: "8776"
    uid: 26794b88-54a2-45c1-a396-849f31322b5c
  spec:
    attacher: driver.longhorn.io
    nodeName: harvesterdev1
    source:
      persistentVolumeName: pvc-0c9a9baf-0cad-4301-9af1-6339ae7a3d7d
  status:
    attached: true
- apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    annotations:
      csi.alpha.kubernetes.io/node-id: harvesterdev1
    creationTimestamp: "2024-08-06T01:57:04Z"
    finalizers:
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:csi.alpha.kubernetes.io/node-id: {}
          f:finalizers:
            .: {}
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T01:57:04Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attacher: {}
          f:nodeName: {}
          f:source:
            f:persistentVolumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:57:04Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:attached: {}
      manager: csi-attacher
      operation: Update
      subresource: status
      time: "2024-08-06T01:57:14Z"
    name: csi-9a5947b5007708414b58eaf79f6fdc6c83cf9a31b18dfbfd973fa035cbe7caea
    resourceVersion: "8693"
    uid: a406347e-bd1e-45fc-bfae-2219eb8662b0
  spec:
    attacher: driver.longhorn.io
    nodeName: harvesterdev1
    source:
      persistentVolumeName: pvc-5cf144c9-2ae0-4981-b5e9-4ae03ebf1569
  status:
    attached: true
- apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    annotations:
      csi.alpha.kubernetes.io/node-id: harvesterdev3
    creationTimestamp: "2024-08-06T02:24:18Z"
    finalizers:
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:csi.alpha.kubernetes.io/node-id: {}
          f:finalizers:
            .: {}
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T02:24:18Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attacher: {}
          f:nodeName: {}
          f:source:
            f:persistentVolumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T02:24:18Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:attached: {}
      manager: csi-attacher
      operation: Update
      subresource: status
      time: "2024-08-06T02:24:32Z"
    name: csi-bec8c2bd22160fa9143c72db95c6c79c2f121a74c8417158e6278376e20dd34f
    resourceVersion: "39616"
    uid: 0b9c8da4-2ca5-47b6-9ba6-62cb5d36001e
  spec:
    attacher: driver.longhorn.io
    nodeName: harvesterdev3
    source:
      persistentVolumeName: pvc-928d5ddc-47de-4481-9c34-abd84a3c9164
  status:
    attached: true
- apiVersion: storage.k8s.io/v1
  kind: VolumeAttachment
  metadata:
    annotations:
      csi.alpha.kubernetes.io/node-id: harvesterdev1
    creationTimestamp: "2024-08-06T01:57:10Z"
    finalizers:
    - external-attacher/driver-longhorn-io
    managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:csi.alpha.kubernetes.io/node-id: {}
          f:finalizers:
            .: {}
            v:"external-attacher/driver-longhorn-io"null: {}
      manager: csi-attacher
      operation: Update
      time: "2024-08-06T01:57:10Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:attacher: {}
          f:nodeName: {}
          f:source:
            f:persistentVolumeName: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:57:10Z"
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:attached: {}
      manager: csi-attacher
      operation: Update
      subresource: status
      time: "2024-08-06T01:57:20Z"
    name: csi-cde06fb7987916086fc1dd4c7ef2c18279c798af6af48c9e5963796f3e167efc
    resourceVersion: "8898"
    uid: 7d3d1605-5687-4640-bd1f-39c2fa8d6760
  spec:
    attacher: driver.longhorn.io
    nodeName: harvesterdev1
    source:
      persistentVolumeName: pvc-3c987c88-f185-48c7-aa17-0efd85c3fbdb
  status:
    attached: true
kind: List
metadata:
  resourceVersion: "770146"
