apiVersion: v1
items:
- apiVersion: crd.projectcalico.org/v1
  kind: IPPool
  metadata:
    annotations:
      projectcalico.org/metadata: '{"uid":"6c856ba7-8312-4366-b6e1-3cb08c7dfd89","creationTimestamp":"2024-08-06T01:51:53Z"}'
    creationTimestamp: "2024-08-06T01:51:53Z"
    generation: 1
    managedFields:
    - apiVersion: crd.projectcalico.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:projectcalico.org/metadata: {}
        f:spec:
          .: {}
          f:allowedUses: {}
          f:blockSize: {}
          f:cidr: {}
          f:ipipMode: {}
          f:natOutgoing: {}
          f:nodeSelector: {}
          f:vxlanMode: {}
      manager: Go-http-client
      operation: Update
      time: "2024-08-06T01:51:53Z"
    name: default-ipv4-ippool
    resourceVersion: "784"
    uid: 8b85f3e8-a198-48dd-932b-64f910203cfa
  spec:
    allowedUses:
    - Workload
    - Tunnel
    blockSize: 26
    cidr: 192.168.0.0/16
    ipipMode: Never
    natOutgoing: true
    nodeSelector: all()
    vxlanMode: Never
kind: List
metadata:
  continue: "null"
  resourceVersion: "770152"
