apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2024-08-06T01:52:47Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:rules: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:52:47Z"
    name: fleet-controller
    namespace: cattle-fleet-system
    resourceVersion: "1634"
    uid: 6339a4a2-e69d-4fba-86b6-cc557301d19f
  rules:
  - apiGroups:
    - "null"
    resources:
    - configmaps
    verbs:
    - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2024-08-06T01:52:47Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:rules: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:52:47Z"
    name: gitjob
    namespace: cattle-fleet-system
    resourceVersion: "1633"
    uid: d9c4ae7e-1b1b-4f26-b779-b4f1dc44a8af
  rules:
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
kind: List
metadata:
  resourceVersion: "770218"
