apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2024-08-06T01:52:47Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:roleRef: {}
        f:subjects: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:52:47Z"
    name: fleet-controller
    namespace: cattle-fleet-system
    resourceVersion: "1635"
    uid: f23dd243-15df-4782-a6cc-0379b45f8996
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: fleet-controller
  subjects:
  - kind: ServiceAccount
    name: fleet-controller
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2024-08-06T01:52:47Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:roleRef: {}
        f:subjects: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:52:47Z"
    name: gitjob
    namespace: cattle-fleet-system
    resourceVersion: "1636"
    uid: 8f1576ca-937b-4611-863f-76d841521562
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gitjob
  subjects:
  - kind: ServiceAccount
    name: gitjob
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2024-08-06T01:57:10Z"
    labels:
      authz.cluster.cattle.io/rtb-owner-updated: p-rm8br_creator-project-owner
      cattle.io/creator: norman
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:authz.cluster.cattle.io/rtb-owner-updated: {}
            f:cattle.io/creator: {}
        f:roleRef: {}
        f:subjects: {}
      manager: rancher
      operation: Update
      time: "2024-08-06T01:57:10Z"
    name: rb-gugqmyot4l
    namespace: cattle-fleet-system
    resourceVersion: "8470"
    uid: 7a2cf3d1-ce84-4645-844d-0293e744d9f8
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: project-owner
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user-xjfbj
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: "2024-08-06T01:57:10Z"
    labels:
      authz.cluster.cattle.io/rtb-owner-updated: p-rm8br_creator-project-owner
      cattle.io/creator: norman
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:authz.cluster.cattle.io/rtb-owner-updated: {}
            f:cattle.io/creator: {}
        f:roleRef: {}
        f:subjects: {}
      manager: rancher
      operation: Update
      time: "2024-08-06T01:57:10Z"
    name: rb-pjzz5ep4pk
    namespace: cattle-fleet-system
    resourceVersion: "8479"
    uid: 1f67b92e-a9fe-4fe8-abc4-3eeec31fc251
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: user-xjfbj
kind: List
metadata:
  resourceVersion: "770218"
