apiVersion: v1
items:
- apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    annotations:
      helmcharts.cattle.io/managed-by: helm-controller
    creationTimestamp: "2024-08-06T01:56:40Z"
    finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
    generation: 2
    managedFields:
    - apiVersion: helm.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:ownerReferences:
            .: {}
            k:{"uid":"d0733070-b71c-42a1-b35c-0070f02c9e6f"}: {}
        f:spec:
          .: {}
          f:chart: {}
          f:repo: {}
          f:valuesContent: {}
          f:version: {}
        f:status: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T01:56:40Z"
    - apiVersion: helm.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:helmcharts.cattle.io/managed-by: {}
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/on-helm-chart-remove"null: {}
        f:status:
          f:jobName: {}
      manager: helm-controller@harvesterdev1
      operation: Update
      time: "2024-08-06T01:56:41Z"
    name: rancher-logging
    namespace: cattle-logging-system
    ownerReferences:
    - apiVersion: harvesterhci.io/v1beta1
      kind: Addon
      name: rancher-logging
      uid: d0733070-b71c-42a1-b35c-0070f02c9e6f
    resourceVersion: "6719"
    uid: 2fd63ad6-4995-434e-b7ba-73cc8630149a
  spec:
    chart: rancher-logging
    repo: http://harvester-cluster-repo.cattle-system.svc/charts
    valuesContent: |
      systemdLogPath: /var/log/journal
      disablePvc: true
      additionalLoggingSources:
        rke2:
          enabled: true
        kubeAudit:
          enabled: true
          auditFilename: "audit.log"
          pathPrefix: "/var/lib/rancher/rke2/server/logs/"
          loggingRef: "harvester-kube-audit-log-ref"
          fluentbit:
            logTag: kube-audit
            tolerations:
            - key: node-role.kubernetes.io/controlplane
              value: "true"
              effect: NoSchedule
            - key: node-role.kubernetes.io/etcd
              value: "true"
              effect: NoExecute
      fluentd:
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 200Mi
      fluentbit:
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
      eventTailer:
        name: harvester-default
        namespace: cattle-logging-system
        controlNamespace: cattle-logging-system
        workloadOverrides:
          containers:
          - image: rancher/harvester-eventrouter:v0.2.0
            name: event-tailer
            resources:
              limits:
                cpu: 100m
                memory: 100Mi
              requests:
                cpu: 20m
                memory: 20Mi
    version: 103.0.0+up3.17.10
  status:
    jobName: helm-install-rancher-logging
kind: List
metadata:
  continue: "null"
  resourceVersion: "770286"
