apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBeTCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNzIyOTA5MDgwMB4XDTI0MDgwNjAxNTEyMFoXDTM0MDgwNDAxNTEy
      MFowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTcyMjkwOTA4MDBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABEVIknm4Aj01WZVAC6VMFNVbO8v1ccUnvCgKi6+p
      L6BwKjjhJHscdm0sXEfbKmzVzYGI8PREFO7+HJ7vhOlZXBmjQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/mkvosSegv9Rg/1sb
      oX/NIEfYNDAKBggqhkjOPQQDAgNIADBFAiB11MuBH4WWBtvzoEkHidHZeDQokcxK
      wpTPtiVvDepgcgIhAKh3lx5DDJ2W/shLxKqDJRv9YzruvDsyJ9QLcM37IHpp
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-08-06T01:55:39Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:55:39Z"
    name: kube-root-ca.crt
    namespace: longhorn-system
    resourceVersion: "4490"
    uid: 38ffd1da-4ca6-4f66-b1f8-f784dc56544d
- apiVersion: v1
  data:
    default-setting.yaml: |-
      default-data-path: /var/lib/harvester/defaultdisk
      taint-toleration: kubevirt.io/drain:NoSchedule
      priority-class: system-cluster-critical
      concurrent-automatic-engine-upgrade-per-node-limit: 3
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2024-08-06T01:55:23Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.6.2
      helm.sh/chart: longhorn-1.6.2
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:default-setting.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:55:23Z"
    name: longhorn-default-setting
    namespace: longhorn-system
    resourceVersion: "4111"
    uid: afb8bb35-04bc-45cd-a2f5-2b8cf75ea4c9
- apiVersion: v1
  data:
    storageclass.yaml: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""
        fsType: "ext4"
        migratable: "true"
        dataLocality: "disabled"
        unmapMarkSnapChainRemoved: "ignored"
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2024-08-06T01:55:23Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.6.2
      helm.sh/chart: longhorn-1.6.2
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:storageclass.yaml: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:55:23Z"
    name: longhorn-storageclass
    namespace: longhorn-system
    resourceVersion: "4113"
    uid: 6f6ecfe3-fda5-4814-867b-b686b843c116
kind: List
metadata:
  resourceVersion: "770271"
