apiVersion: v1
items:
- apiVersion: v1
  data:
    config: |
      agentCheckinInterval: 15m
      agentImage: rancher/fleet-agent:v0.9.2
      agentImagePullPolicy: IfNotPresent
      apiServerCA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQVdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKYkdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNVGN5TWprdwpPVEUxTVRBZUZ3MHlOREE0TURZd01UVXlNekZhRncwek5EQTRNRFF3TVRVeU16RmFNRVl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56SXlPVEE1TVRVeE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWQrUjFsYlFiaUZ6Mwp0eVZqR2tLdE15a3ZhRUgwUC81VzRGc3dWcm52SVJnbkpLVnU2QVlCM1VhSzdMWVRETzRKVnV5ZUVxVys5N3R5CjNvaVc3dzliYTZOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT1RaTklWNWo3alFkVlprK0VEbklsZ2o0d20vTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNaQwprZWd4THlnNHJNNEhhVnloMW42MHdZbkdjSlQ5K2tWYUU0NGZSTDRNQWlCaFpOOVhNaU5sQXdId1dMczdtaGpyCkxuaks3RUhsRFU1cE9NcmdEdFFObEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      apiServerURL: https://10.53.97.255
      bootstrap:
        agentNamespace: cattle-fleet-local-system
        branch: master
        namespace: fleet-local
        paths: ""
        repo: ""
        secret: ""
      githubURLPrefix: ""
      ignoreClusterRegistrationLabels: false
      systemDefaultRegistry: ""
      webhookReceiverURL: ""
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: fleet
      meta.helm.sh/release-namespace: cattle-fleet-system
    creationTimestamp: "2024-08-06T01:52:47Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
      manager: helm
      operation: Update
      time: "2024-08-06T02:14:17Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          f:config: {}
      manager: harvester
      operation: Update
      time: "2024-08-06T02:14:20Z"
    name: fleet-controller
    namespace: cattle-fleet-system
    resourceVersion: "27962"
    uid: fa87f6f9-c583-42fe-bfb9-3c39c371e58a
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBeTCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNzIyOTA5MDgwMB4XDTI0MDgwNjAxNTEyMFoXDTM0MDgwNDAxNTEy
      MFowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTcyMjkwOTA4MDBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABEVIknm4Aj01WZVAC6VMFNVbO8v1ccUnvCgKi6+p
      L6BwKjjhJHscdm0sXEfbKmzVzYGI8PREFO7+HJ7vhOlZXBmjQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/mkvosSegv9Rg/1sb
      oX/NIEfYNDAKBggqhkjOPQQDAgNIADBFAiB11MuBH4WWBtvzoEkHidHZeDQokcxK
      wpTPtiVvDepgcgIhAKh3lx5DDJ2W/shLxKqDJRv9YzruvDsyJ9QLcM37IHpp
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-08-06T01:52:41Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:52:41Z"
    name: kube-root-ca.crt
    namespace: cattle-fleet-system
    resourceVersion: "1560"
    uid: 5ee34912-1302-4061-9e04-f08f03156a95
kind: List
metadata:
  resourceVersion: "770218"
