apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2024-08-06T01:52:49Z"
    creationTimestamp: "2024-08-06T01:52:47Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:endpoints.kubernetes.io/last-change-trigger-time: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
        f:subsets: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:52:49Z"
    name: gitjob
    namespace: cattle-fleet-system
    resourceVersion: "1707"
    uid: 5c395678-6ae1-4323-b99f-a615b5d8e12b
  subsets:
  - addresses:
    - ip: 10.52.0.12
      nodeName: harvesterdev1
      targetRef:
        kind: Pod
        name: gitjob-848764c58b-t4bth
        namespace: cattle-fleet-system
        uid: a50f4fd2-e4e5-4f68-8c79-6117b9181a3c
    ports:
    - name: http-80
      port: 8080
      protocol: TCP
kind: List
metadata:
  resourceVersion: "770218"
