apiVersion: v1
items:
- apiVersion: scheduling.k8s.io/v1
  description: This priority class should be used for core kubevirt components only.
  kind: PriorityClass
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2024-08-06T01:55:23Z"
    generation: 1
    labels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: virt-operator
      app.kubernetes.io/part-of: kubevirt-operator
      app.kubernetes.io/version: 0.30.x
      helm.sh/chart: kubevirt-operator-0.2.0
      helm.sh/release: harvester
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: scheduling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:description: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:helm.sh/release: {}
            f:objectset.rio.cattle.io/hash: {}
        f:preemptionPolicy: {}
        f:value: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:55:23Z"
    name: kubevirt-cluster-critical
    resourceVersion: "4082"
    uid: 790aef08-2894-4838-bdb3-66dbd259474b
  preemptionPolicy: PreemptLowerPriority
  value: 1e+09
- apiVersion: scheduling.k8s.io/v1
  description: Ensure Longhorn pods have the highest priority to prevent any unexpected
    eviction by the Kubernetes scheduler under node pressure
  kind: PriorityClass
  metadata:
    annotations:
      meta.helm.sh/release-name: harvester
      meta.helm.sh/release-namespace: harvester-system
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    creationTimestamp: "2024-08-06T01:55:23Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.6.2
      helm.sh/chart: longhorn-1.6.2
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
    managedFields:
    - apiVersion: scheduling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:description: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:objectset.rio.cattle.io/hash: {}
        f:preemptionPolicy: {}
        f:value: {}
      manager: fleetagent
      operation: Update
      time: "2024-08-06T01:55:23Z"
    name: longhorn-critical
    resourceVersion: "4081"
    uid: 47dff957-f8a6-427e-a778-536e4d87dbaa
  preemptionPolicy: PreemptLowerPriority
  value: 1e+09
- apiVersion: scheduling.k8s.io/v1
  description: Priority class used by pods critical to rancher's functionality.
  kind: PriorityClass
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher
      meta.helm.sh/release-namespace: cattle-system
    creationTimestamp: "2024-08-06T01:51:34Z"
    generation: 1
    labels:
      app: rancher
      app.kubernetes.io/managed-by: Helm
      chart: rancher-2.8.3-dirty.commit-904c2fb09
      heritage: Helm
      release: rancher
    managedFields:
    - apiVersion: scheduling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:description: {}
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
        f:preemptionPolicy: {}
        f:value: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:51:34Z"
    name: rancher-critical
    resourceVersion: "298"
    uid: e77ae20d-8950-48ee-b24b-0e8d28738bd9
  preemptionPolicy: PreemptLowerPriority
  value: 1e+09
- apiVersion: scheduling.k8s.io/v1
  description: Used for system critical pods that must run in the cluster, but can
    be moved to another node if necessary.
  kind: PriorityClass
  metadata:
    creationTimestamp: "2024-08-06T01:51:31Z"
    generation: 1
    managedFields:
    - apiVersion: scheduling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:description: {}
        f:preemptionPolicy: {}
        f:value: {}
      manager: kube-apiserver
      operation: Update
      time: "2024-08-06T01:51:31Z"
    name: system-cluster-critical
    resourceVersion: "73"
    uid: 1498ae16-72c0-4164-b4a4-167dfdc6a311
  preemptionPolicy: PreemptLowerPriority
  value: 2e+09
- apiVersion: scheduling.k8s.io/v1
  description: Used for system critical pods that must not be moved from their current
    node.
  kind: PriorityClass
  metadata:
    creationTimestamp: "2024-08-06T01:51:31Z"
    generation: 1
    managedFields:
    - apiVersion: scheduling.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:description: {}
        f:preemptionPolicy: {}
        f:value: {}
      manager: kube-apiserver
      operation: Update
      time: "2024-08-06T01:51:31Z"
    name: system-node-critical
    resourceVersion: "72"
    uid: 62c3e026-a165-4e2b-96db-e9fc47e6adda
  preemptionPolicy: PreemptLowerPriority
  value: 2.000001e+09
kind: List
metadata:
  resourceVersion: "770152"
