apiVersion: v1
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: cloud-controller-manager
    usage:
      cpu: 2096402n
      memory: 28352Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: cloud-controller-manager
      tier: control-plane
    name: cloud-controller-manager-harvesterdev1
    namespace: kube-system
  timestamp: "2024-08-06T14:12:00Z"
  window: 12.619s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: etcd
    usage:
      cpu: 102561565n
      memory: 390268Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: etcd
      tier: control-plane
    name: etcd-harvesterdev1
    namespace: kube-system
  timestamp: "2024-08-06T14:11:56Z"
  window: 12.242s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: snapshot-validation-webhook
    usage:
      cpu: 1706729n
      memory: 20052Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: snapshot-validation-webhook
      pod-template-hash: b75f94bcb
    name: harvester-snapshot-validation-webhook-b75f94bcb-sghrd
    namespace: kube-system
  timestamp: "2024-08-06T14:11:50Z"
  window: 25.247s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: snapshot-validation-webhook
    usage:
      cpu: 1099886n
      memory: 21760Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: snapshot-validation-webhook
      pod-template-hash: b75f94bcb
    name: harvester-snapshot-validation-webhook-b75f94bcb-xf7n6
    namespace: kube-system
  timestamp: "2024-08-06T14:11:52Z"
  window: 17.647s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: whereabouts
    usage:
      cpu: 69144n
      memory: 23108Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: whereabouts
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: whereabouts
      controller-revision-hash: 75c8fc64ff
      name: whereabouts
      pod-template-generation: "1"
    name: harvester-whereabouts-2bpm7
    namespace: kube-system
  timestamp: "2024-08-06T14:11:57Z"
  window: 13.657s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: whereabouts
    usage:
      cpu: 109767n
      memory: 27016Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: whereabouts
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: whereabouts
      controller-revision-hash: 75c8fc64ff
      name: whereabouts
      pod-template-generation: "1"
    name: harvester-whereabouts-5m97d
    namespace: kube-system
  timestamp: "2024-08-06T14:11:58Z"
  window: 10.694s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: whereabouts
    usage:
      cpu: 23124n
      memory: 26884Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: whereabouts
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: whereabouts
      controller-revision-hash: 75c8fc64ff
      name: whereabouts
      pod-template-generation: "1"
    name: harvester-whereabouts-9qs8g
    namespace: kube-system
  timestamp: "2024-08-06T14:12:03Z"
  window: 13.045s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: whereabouts
    usage:
      cpu: 46534n
      memory: 27792Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: whereabouts
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: whereabouts
      controller-revision-hash: 75c8fc64ff
      name: whereabouts
      pod-template-generation: "1"
    name: harvester-whereabouts-cphbg
    namespace: kube-system
  timestamp: "2024-08-06T14:11:51Z"
  window: 19.534s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-apiserver
    usage:
      cpu: 673718118n
      memory: 2617000Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-apiserver
      tier: control-plane
    name: kube-apiserver-harvesterdev1
    namespace: kube-system
  timestamp: "2024-08-06T14:11:58Z"
  window: 10.511s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-controller-manager
    usage:
      cpu: 17094146n
      memory: 172116Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-controller-manager
      tier: control-plane
    name: kube-controller-manager-harvesterdev1
    namespace: kube-system
  timestamp: "2024-08-06T14:12:01Z"
  window: 13.012s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-proxy
    usage:
      cpu: 608172n
      memory: 29184Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-proxy
      tier: control-plane
    name: kube-proxy-harvesterdev1
    namespace: kube-system
  timestamp: "2024-08-06T14:11:49Z"
  window: 19.841s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-proxy
    usage:
      cpu: 479781n
      memory: 27276Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-proxy
      tier: control-plane
    name: kube-proxy-harvesterdev2
    namespace: kube-system
  timestamp: "2024-08-06T14:12:06Z"
  window: 29.042s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-proxy
    usage:
      cpu: 677783n
      memory: 25232Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-proxy
      tier: control-plane
    name: kube-proxy-harvesterdev3
    namespace: kube-system
  timestamp: "2024-08-06T14:11:52Z"
  window: 11.682s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-proxy
    usage:
      cpu: 686780n
      memory: 24956Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-proxy
      tier: control-plane
    name: kube-proxy-harvesterdev7
    namespace: kube-system
  timestamp: "2024-08-06T14:12:00Z"
  window: 16.054s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-scheduler
    usage:
      cpu: 4776587n
      memory: 41220Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      component: kube-scheduler
      tier: control-plane
    name: kube-scheduler-harvesterdev1
    namespace: kube-system
  timestamp: "2024-08-06T14:12:06Z"
  window: 30.767s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 20624074n
      memory: 27464Ki
  - name: calico-node
    usage:
      cpu: 30829747n
      memory: 128680Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      controller-revision-hash: 59f689fcb
      k8s-app: canal
      pod-template-generation: "1"
    name: rke2-canal-5x7kr
    namespace: kube-system
  timestamp: "2024-08-06T14:11:54Z"
  window: 11.137s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 11327287n
      memory: 26788Ki
  - name: calico-node
    usage:
      cpu: 24169193n
      memory: 122896Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      controller-revision-hash: 59f689fcb
      k8s-app: canal
      pod-template-generation: "1"
    name: rke2-canal-gssgp
    namespace: kube-system
  timestamp: "2024-08-06T14:11:54Z"
  window: 18.237s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-flannel
    usage:
      cpu: 18035968n
      memory: 26428Ki
  - name: calico-node
    usage:
      cpu: 26521716n
      memory: 121812Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      controller-revision-hash: 59f689fcb
      k8s-app: canal
      pod-template-generation: "1"
    name: rke2-canal-jwqrp
    namespace: kube-system
  timestamp: "2024-08-06T14:11:49Z"
  window: 13.704s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: calico-node
    usage:
      cpu: 23353336n
      memory: 116224Ki
  - name: kube-flannel
    usage:
      cpu: 9576304n
      memory: 26768Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      controller-revision-hash: 59f689fcb
      k8s-app: canal
      pod-template-generation: "1"
    name: rke2-canal-pwhs8
    namespace: kube-system
  timestamp: "2024-08-06T14:12:00Z"
  window: 13.139s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: coredns
    usage:
      cpu: 2221852n
      memory: 36268Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/instance: rke2-coredns
      app.kubernetes.io/name: rke2-coredns
      k8s-app: kube-dns
      pod-template-hash: 864fbd7785
    name: rke2-coredns-rke2-coredns-864fbd7785-bwfcp
    namespace: kube-system
  timestamp: "2024-08-06T14:11:59Z"
  window: 10.229s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: coredns
    usage:
      cpu: 1605103n
      memory: 38588Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/instance: rke2-coredns
      app.kubernetes.io/name: rke2-coredns
      k8s-app: kube-dns
      pod-template-hash: 864fbd7785
    name: rke2-coredns-rke2-coredns-864fbd7785-jc77s
    namespace: kube-system
  timestamp: "2024-08-06T14:12:05Z"
  window: 26.465s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: autoscaler
    usage:
      cpu: 180413n
      memory: 20616Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/instance: rke2-coredns
      app.kubernetes.io/name: rke2-coredns-autoscaler
      k8s-app: kube-dns-autoscaler
      pod-template-hash: 6c87968579
    name: rke2-coredns-rke2-coredns-autoscaler-6c87968579-cfkt6
    namespace: kube-system
  timestamp: "2024-08-06T14:11:55Z"
  window: 16.515s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: rke2-ingress-nginx-controller
    usage:
      cpu: 5318315n
      memory: 478476Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: rke2-ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rke2-ingress-nginx
      app.kubernetes.io/part-of: rke2-ingress-nginx
      app.kubernetes.io/version: 1.9.6
      controller-revision-hash: 58b87fbbb
      helm.sh/chart: rke2-ingress-nginx-4.9.100
      pod-template-generation: "2"
    name: rke2-ingress-nginx-controller-ddpjc
    namespace: kube-system
  timestamp: "2024-08-06T14:11:52Z"
  window: 11.628s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: rke2-ingress-nginx-controller
    usage:
      cpu: 5038355n
      memory: 417556Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: rke2-ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rke2-ingress-nginx
      app.kubernetes.io/part-of: rke2-ingress-nginx
      app.kubernetes.io/version: 1.9.6
      controller-revision-hash: 58b87fbbb
      helm.sh/chart: rke2-ingress-nginx-4.9.100
      pod-template-generation: "2"
    name: rke2-ingress-nginx-controller-gtgfl
    namespace: kube-system
  timestamp: "2024-08-06T14:12:06Z"
  window: 27.523s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: rke2-ingress-nginx-controller
    usage:
      cpu: 9966459n
      memory: 881900Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: rke2-ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rke2-ingress-nginx
      app.kubernetes.io/part-of: rke2-ingress-nginx
      app.kubernetes.io/version: 1.9.6
      controller-revision-hash: 58b87fbbb
      helm.sh/chart: rke2-ingress-nginx-4.9.100
      pod-template-generation: "2"
    name: rke2-ingress-nginx-controller-kvsmb
    namespace: kube-system
  timestamp: "2024-08-06T14:12:06Z"
  window: 25.622s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: rke2-ingress-nginx-controller
    usage:
      cpu: 6413454n
      memory: 418916Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: rke2-ingress-nginx
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rke2-ingress-nginx
      app.kubernetes.io/part-of: rke2-ingress-nginx
      app.kubernetes.io/version: 1.9.6
      controller-revision-hash: 58b87fbbb
      helm.sh/chart: rke2-ingress-nginx-4.9.100
      pod-template-generation: "2"
    name: rke2-ingress-nginx-controller-kz8qf
    namespace: kube-system
  timestamp: "2024-08-06T14:11:56Z"
  window: 11.807s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: metrics-server
    usage:
      cpu: 3783240n
      memory: 43560Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: rke2-metrics-server
      app.kubernetes.io/instance: rke2-metrics-server
      app.kubernetes.io/name: rke2-metrics-server
      pod-template-hash: 7f745dbddf
    name: rke2-metrics-server-7f745dbddf-5trhx
    namespace: kube-system
  timestamp: "2024-08-06T14:12:05Z"
  window: 16.212s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-rke2-multus
    usage:
      cpu: "0"
      memory: 35212Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: rke2-multus
      controller-revision-hash: 78f6bc8dc
      pod-template-generation: "1"
      tier: node
    name: rke2-multus-2pxj6
    namespace: kube-system
  timestamp: "2024-08-06T14:11:51Z"
  window: 17.927s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-rke2-multus
    usage:
      cpu: 1622n
      memory: 37332Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: rke2-multus
      controller-revision-hash: 78f6bc8dc
      pod-template-generation: "1"
      tier: node
    name: rke2-multus-4g2jg
    namespace: kube-system
  timestamp: "2024-08-06T14:12:03Z"
  window: 21.621s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-rke2-multus
    usage:
      cpu: "0"
      memory: 35156Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: rke2-multus
      controller-revision-hash: 78f6bc8dc
      pod-template-generation: "1"
      tier: node
    name: rke2-multus-8wp2w
    namespace: kube-system
  timestamp: "2024-08-06T14:12:01Z"
  window: 15.104s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: kube-rke2-multus
    usage:
      cpu: 899n
      memory: 35108Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: rke2-multus
      controller-revision-hash: 78f6bc8dc
      pod-template-generation: "1"
      tier: node
    name: rke2-multus-w5rcx
    namespace: kube-system
  timestamp: "2024-08-06T14:11:59Z"
  window: 28.946s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: snapshot-controller
    usage:
      cpu: 100184n
      memory: 16140Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: snapshot-controller
      pod-template-hash: 65d5f465d9
    name: snapshot-controller-65d5f465d9-bbk25
    namespace: kube-system
  timestamp: "2024-08-06T14:12:02Z"
  window: 11.69s
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: snapshot-controller
    usage:
      cpu: 433333n
      memory: 19100Ki
  kind: PodMetrics
  metadata:
    creationTimestamp: "2024-08-06T14:12:14Z"
    labels:
      app: snapshot-controller
      pod-template-hash: 65d5f465d9
    name: snapshot-controller-65d5f465d9-ssxbd
    namespace: kube-system
  timestamp: "2024-08-06T14:11:55Z"
  window: 11.401s
kind: List
metadata: {}
