apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Logging
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-logging
      meta.helm.sh/release-namespace: cattle-logging-system
    creationTimestamp: "2024-08-06T01:56:42Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: rancher-logging
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-logging
      app.kubernetes.io/version: 3.17.10
      helm.sh/chart: rancher-logging-103.0.0_up3.17.10
    managedFields:
    - apiVersion: logging.banzaicloud.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          .: {}
          f:controlNamespace: {}
          f:fluentbit:
            .: {}
            f:disableKubernetesFilter: {}
            f:extraVolumeMounts: {}
            f:image:
              .: {}
              f:repository: {}
              f:tag: {}
            f:inputTail:
              .: {}
              f:Parser: {}
              f:Path: {}
              f:Tag: {}
            f:nodeSelector:
              .: {}
              f:kubernetes.io/os: {}
              f:node-role.kubernetes.io/master: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:tolerations: {}
          f:fluentd:
            .: {}
            f:configReloaderImage:
              .: {}
              f:repository: {}
              f:tag: {}
            f:disablePvc: {}
            f:image:
              .: {}
              f:repository: {}
              f:tag: {}
            f:livenessProbe:
              .: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:tcpSocket:
                .: {}
                f:port: {}
            f:nodeSelector:
              .: {}
              f:kubernetes.io/os: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:security:
              .: {}
              f:podSecurityContext:
                .: {}
                f:runAsUser: {}
            f:tolerations: {}
          f:loggingRef: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:42Z"
    - apiVersion: logging.banzaicloud.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:configCheckResults:
            .: {}
            f:ac2d4553: {}
      manager: manager
      operation: Update
      subresource: status
      time: "2024-08-06T01:56:56Z"
    name: rancher-logging-kube-audit
    resourceVersion: "7483"
    uid: 6c38f044-6c60-471b-9fe8-8682d6f7f12f
  spec:
    controlNamespace: cattle-logging-system
    fluentbit:
      disableKubernetesFilter: true
      extraVolumeMounts:
      - destination: /kube-audit-logs
        readOnly: true
        source: /var/lib/rancher/rke2/server/logs/
      image:
        repository: rancher/mirrored-fluent-fluent-bit
        tag: 2.2.0
      inputTail:
        Parser: json
        Path: /kube-audit-logs/audit.log
        Tag: kube-audit
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/master: "true"
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: "true"
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: "true"
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: "true"
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: "true"
    fluentd:
      configReloaderImage:
        repository: rancher/mirrored-jimmidyson-configmap-reload
        tag: v0.4.0
      disablePvc: true
      image:
        repository: rancher/mirrored-banzaicloud-fluentd
        tag: v1.14.6-alpine-5
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 15
        tcpSocket:
          port: 24240
      nodeSelector:
        kubernetes.io/os: linux
      resources:
        limits:
          cpu: 1000m
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 200Mi
      security:
        podSecurityContext:
          runAsUser: 100
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
    loggingRef: harvester-kube-audit-log-ref
  status:
    configCheckResults:
      ac2d4553: true
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Logging
  metadata:
    annotations:
      meta.helm.sh/release-name: rancher-logging
      meta.helm.sh/release-namespace: cattle-logging-system
    creationTimestamp: "2024-08-06T01:56:42Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: rancher-logging
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rancher-logging
      app.kubernetes.io/version: 3.17.10
      helm.sh/chart: rancher-logging-103.0.0_up3.17.10
    managedFields:
    - apiVersion: logging.banzaicloud.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          .: {}
          f:controlNamespace: {}
          f:fluentbit:
            .: {}
            f:image:
              .: {}
              f:repository: {}
              f:tag: {}
            f:nodeSelector:
              .: {}
              f:kubernetes.io/os: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:tolerations: {}
          f:fluentd:
            .: {}
            f:configReloaderImage:
              .: {}
              f:repository: {}
              f:tag: {}
            f:disablePvc: {}
            f:image:
              .: {}
              f:repository: {}
              f:tag: {}
            f:livenessProbe:
              .: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:tcpSocket:
                .: {}
                f:port: {}
            f:nodeSelector:
              .: {}
              f:kubernetes.io/os: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:security:
              .: {}
              f:podSecurityContext:
                .: {}
                f:runAsUser: {}
            f:tolerations: {}
      manager: helm
      operation: Update
      time: "2024-08-06T01:56:42Z"
    - apiVersion: logging.banzaicloud.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:configCheckResults:
            .: {}
            f:ac2d4553: {}
      manager: manager
      operation: Update
      subresource: status
      time: "2024-08-06T01:56:58Z"
    name: rancher-logging-root
    resourceVersion: "7550"
    uid: 85f92fa1-f975-4870-b687-35338bb55767
  spec:
    controlNamespace: cattle-logging-system
    fluentbit:
      image:
        repository: rancher/mirrored-fluent-fluent-bit
        tag: 2.2.0
      nodeSelector:
        kubernetes.io/os: linux
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
      - effect: NoSchedule
        key: node-role.kubernetes.io/controlplane
        value: "true"
      - effect: NoExecute
        key: node-role.kubernetes.io/etcd
        value: "true"
    fluentd:
      configReloaderImage:
        repository: rancher/mirrored-jimmidyson-configmap-reload
        tag: v0.4.0
      disablePvc: true
      image:
        repository: rancher/mirrored-banzaicloud-fluentd
        tag: v1.14.6-alpine-5
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 15
        tcpSocket:
          port: 24240
      nodeSelector:
        kubernetes.io/os: linux
      resources:
        limits:
          cpu: 1000m
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 200Mi
      security:
        podSecurityContext:
          runAsUser: 100
      tolerations:
      - effect: NoSchedule
        key: cattle.io/os
        operator: Equal
        value: linux
  status:
    configCheckResults:
      ac2d4553: true
kind: List
metadata:
  continue: "null"
  resourceVersion: "770167"
