apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBeTCCAR+gAwIBAgIBADAKBggqhkjOPQQDAjAkMSIwIAYDVQQDDBlya2UyLXNl
      cnZlci1jYUAxNzIyOTA5MDgwMB4XDTI0MDgwNjAxNTEyMFoXDTM0MDgwNDAxNTEy
      MFowJDEiMCAGA1UEAwwZcmtlMi1zZXJ2ZXItY2FAMTcyMjkwOTA4MDBZMBMGByqG
      SM49AgEGCCqGSM49AwEHA0IABEVIknm4Aj01WZVAC6VMFNVbO8v1ccUnvCgKi6+p
      L6BwKjjhJHscdm0sXEfbKmzVzYGI8PREFO7+HJ7vhOlZXBmjQjBAMA4GA1UdDwEB
      /wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ/mkvosSegv9Rg/1sb
      oX/NIEfYNDAKBggqhkjOPQQDAgNIADBFAiB11MuBH4WWBtvzoEkHidHZeDQokcxK
      wpTPtiVvDepgcgIhAKh3lx5DDJ2W/shLxKqDJRv9YzruvDsyJ9QLcM37IHpp
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2024-08-06T01:52:31Z"
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:ca.crt: {}
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/description: {}
      manager: kube-controller-manager
      operation: Update
      time: "2024-08-06T01:52:31Z"
    name: kube-root-ca.crt
    namespace: local
    resourceVersion: "1447"
    uid: 7bbde3cc-b2db-438e-a33e-0579deb6868e
kind: List
metadata:
  resourceVersion: "770267"
